name: linux

on: [push]

jobs:
  build_package:
    name: Build Tcl extension for Tcl 8 and 9 on manylinux_2014
    runs-on: ubuntu-latest

    container:
      image: quay.io/pypa/manylinux2014_x86_64

    steps:
      - name: Checkout
        run:
          git clone https://github.com/3-manifolds/TkGL


      - name: install wget
        run:
          yum install wget

      - name: Run build script
        run:
          cd TkGL
          bash ./ci/linux/build_linux_tkgl.sh

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TkGL_pkg_linux
          path: ./dist
