name: linux

on: [push]

jobs:
  build_package:
    name: Build Tcl extension for Tcl 8 and 9 on ubuntu
    runs-on: ubuntu-22.94
    container: quay.io/pypa/manylinux2014_x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install Mesa
        run: |
          sudo apt-get update
          sudo apt-get install libgl-dev libglx-dev

      - name: Run build script
        run: |
          bash ./ci/linux/build_linux_tkgl.sh

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TkGL_package
          path: ./dist