name: macOS

on: [push]

jobs:
  build_package:
    name: Build Tcl extension for Tcl 8 and 9 on macOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run build script
        run: |
          bash ./ci/macOS/build_mac_tkgl.sh

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TkGL_pkg_macOS
          path: ./dist