name: manylinux-arm64

on: [push]

jobs:
  build_package:
    name: Build Tcl extension for Tcl 8 and 9 on manylinux_2_28
    runs-on: ubuntu-22.04-arm

    container:
      image: quay.io/pypa/manylinux_2_28_aarch64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install wget
        run:
          yum install -y wget zip

      - name: Run build script
        run: |
          bash ./ci/linux/build_linux_tkgl.sh

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TkGL_pkg_manylinux_aarch64
          path: ./dist
